import express from 'express';
import LoginController from '../Controllers/LoginController';
const router = express.Router();
import SignupController from '../Controllers/RegisterController';
import LoginGoogleController from '../Controllers/LoginGoogleController';
import GetNewAccessToken from '../Controllers/GetNewAccessToken';
import Authenticate from '../Controllers/Authenticate';
router.route('/signup').post(SignupController);
router.route('/login').post(LoginController);
router.route('/refreshToken').post(GetNewAccessToken);
router.route('/googleLogin').post(LoginGoogleController);
router.route('/authenticate').post(Authenticate);
export default router;
